# --------------------------------------
# -- Init master k8s node
# --------------------------------------
---
- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Create config file from template
  template:
    src: master-node.j2
    dest: "/tmp/init-config.yaml"
  register: kubernetes_init_config
  when: kubernetes_init_config is not defined

- name: Initialize Kubernetes master with kubeadm init.
  become: true
  command: >
    kubeadm init --config /tmp/init-config.yaml
  register: kubeadmin_init
  when: not kubernetes_init_stat.stat.exists

- name: Ensure .kube directory exists.
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: "~/.kube/config"
    state: link
    mode: 0644

- name: Storing config on the local machine
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./
    flat: yes

- name: Get the kubeadm join command.
  command: kubeadm token create --print-join-command
  register: kubernetes_join_command_result

- name: Set join command
  set_fact:
    kubernetes_join_command: "{{ kubernetes_join_command_result.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ all_hosts }}"

- name: Configure Flannel networking.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f {{ kubernetes_flannel_manifest_file_rbac }}
    - kubectl apply -f {{ kubernetes_flannel_manifest_file }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"

- name: Download Helm archieve.
  command: "wget https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz"

- name: Unpack Helm archieve.
  command: "tar xvf helm-v3.9.3-linux-amd64.tar.gz"

- name: Move Helm to /usr/local/bin.
  command: "mv linux-amd64/helm /usr/local/bin"

- name: Clear workspace.
  command: "rm -rf linux-amd64 helm-v3.9.3-linux-amd64.tar.gz"

