apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-db
spec:
  selector:
    matchLabels:
      app: testapp-db
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: testapp-db
    spec:
      containers:
        - name: testapp-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: testapp-postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: tutorial-dev
            - name: POSTGRES_USER
              value: vinhle
            - name: POSTGRES_PASSWORD
              value: password
          resources:
           limits:
              memory: 4Gi
              cpu: "2"
      volumes:
        - name: testapp-postgres-data-storage
          persistentVolumeClaim:
            claimName: testapp-postgres-data-persisent-volume-claim
