# db-persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testapp-postgres-data-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: testapp-postgres-data-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/testapp-postgres-data"

