# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: testapp-db-service
spec:
  type: NodePort
  selector:
    app: testapp-db
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432

