# web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: testapp-web-service
spec:
  type: NodePort
  selector:
    app: testapp-web
  ports:
    - name: "http"
      protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30000
