# web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-web
spec:
  selector:
    matchLabels:
      app: testapp-web
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: testapp-web
    spec:
      containers:
        - name: testapp-web
          image: thepit/testapp:latest
          ports:
            - containerPort: 3003
              name: "http"
          env:
            - name: POSTGRES_DB
              value: tutorial-dev
            - name: POSTGRES_USER
              value: vinhle
            - name: POSTGRES_PASSWORD
              value: password
            - name: CUSTOMCONNSTR_TestappContext
              value: Host=$(TESTAPP_DB_SERVICE_SERVICE_HOST);Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)
          resources:
            limits:
              memory: 8Gi
              cpu: "4"
